# Generated by Django 5.0.2 on 2024-04-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['last_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleadosss'},
        ),
        migrations.AlterModelOptions(
            name='habilidades',
            options={'ordering': ['id'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades Empleadosss'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre Completo'),
        ),
    ]
